---
- hosts: app
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add repository into sources list
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Setup docker user
      remote_user: ubuntu
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: change file ownership
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: ubuntu
        group: ubuntu

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install aws-cli
      apt:
        name: awscli
        state: present
        update_cache: yes
  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted
